services:
  laravelapp:
    container_name: laravelapp
    image: dkalabukhov/crud-app:1.0.3
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1998
      POSTRGRES_DB: users
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}